version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./static/postgres-data:/data/postgres
    ports:
      - '5432:5432'
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${DB_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    ports:
      - '54321:80'
    depends_on:
      - postgres
    networks:
      - postgres

  redis:
    container_name: redis-cache
    image: redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - ./static/redis-data:/data

  redisinsight:
    container_name: redis-insight
    image: redis/redisinsight:latest
    restart: unless-stopped
    ports:
      - 5540:5540
    volumes:
      - ./static/redisinsight-data:/data
    depends_on:
      - redis

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  redis:
  redisinsight:
