all:
	C:\TDM-GCC-64\bin\g++.exe -Wall -Wextra -g3 *.cpp -o output\forca.exe

	 .\output\forca.exe

run:
	output\forca.exe

link:
	C:\TDM-GCC-64\bin\g++.exe -c *.cpp

	C:\TDM-GCC-64\bin\g++.exe -Wall -Wextra -g3 forca.cpp -o output\forca.exe

	g++ *.o -o output\forca.exe